export default {
    darkMode: ["class"],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-dim": "#38ecd8",
                "surface-dim": "#0e0e0e",
                "secondary-fixed": "#4efbe6",
                "primary-container": "#aa92f0",
                "surface-container": "#1a1919",
                "surface-bright": "#2c2c2c",
                "error-container": "#a70138",
                "on-tertiary-container": "#2a0070",
                "primary-fixed": "#b89fff",
                "surface-container-highest": "#262626",
                "inverse-on-surface": "#565555",
                "secondary-fixed-dim": "#38ecd8",
                "on-tertiary-fixed": "#1e0054",
                "on-secondary-fixed": "#004841",
                "surface-tint": "#b89fff",
                "on-error-container": "#ffb2b9",
                "tertiary-container": "#ac8eff",
                "inverse-surface": "#fcf9f8",
                "tertiary-dim": "#a98bfc",
                "tertiary-fixed-dim": "#ae91ff",
                "on-secondary-fixed-variant": "#00675d",
                "primary-fixed-dim": "#aa92f0",
                "on-surface": "#ffffff",
                "secondary": "#4efbe6",
                "on-primary-fixed-variant": "#3e257e",
                "on-tertiary-fixed-variant": "#421f8f",
                "surface-container-low": "#131313",
                "surface-variant": "#262626",
                "on-background": "#ffffff",
                "inverse-primary": "#674fa9",
                "tertiary-fixed": "#bba2ff",
                "surface": "#0e0e0e",
                "on-primary-fixed": "#19004b",
                "primary-dim": "#aa92f0",
                "on-primary-container": "#290769",
                "error-dim": "#d73357",
                "secondary-container": "#006a60",
                "outline-variant": "#484847",
                "outline": "#767575",
                "on-secondary-container": "#dcfff8",
                "primary": "#b89fff",
                "on-primary": "#351a75",
                "background": "#0e0e0e",
                "surface-container-high": "#201f1f",
                "on-tertiary": "#370e84",
                "on-error": "#490013",
                "on-surface-variant": "#adaaaa",
                "on-secondary": "#005c53",
                "surface-container-lowest": "#000000",
                "error": "#ff6e84",
                "tertiary": "#b89fff"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        }
    },
    plugins: [],
}
